import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdmin } from "@/lib/auth/session";
import { db } from "@/lib/db";
import { apiError, requireSameOrigin } from "@/lib/http";
import { normalizeAnswer } from "@/lib/scoring/normalize";
const itemSchema=z.object({id:z.string(),externalId:z.string(),number:z.number().int(),prompt:z.string(),keyword:z.string().nullable(),baseWord:z.string().nullable(),variants:z.array(z.object({answer:z.string().min(1),points:z.number().int().min(0).max(10)})).min(1),maximumPoints:z.number().int().min(1).max(10),explanation:z.string(),active:z.boolean()});
const schema=z.object({externalId:z.string(),title:z.string().min(1),instructions:z.string(),fullText:z.string().min(1),notes:z.string(),transcriptionStatus:z.string().min(1),active:z.boolean(),items:z.array(itemSchema)});
export async function PATCH(request:Request,{params}:{params:Promise<{setId:string}>}){try{requireSameOrigin(request);await requireAdmin();const {setId}=await params;const input=schema.parse(await request.json());if(input.externalId!==setId)throw new Error('FORBIDDEN');const existing=await db.exerciseSet.findUnique({where:{externalId:setId},select:{id:true}});if(!existing)throw new Error('NOT_FOUND');await db.$transaction(async tx=>{await tx.exerciseSet.update({where:{id:existing.id},data:{title:input.title,instructions:input.instructions,fullText:input.fullText,notes:input.notes,transcriptionStatus:input.transcriptionStatus,active:input.active,contentVersion:{increment:1}}});for(const item of input.items){const row=await tx.exerciseItem.findFirst({where:{id:item.id,exerciseSetId:existing.id}});if(!row)throw new Error('FORBIDDEN');await tx.exerciseItem.update({where:{id:item.id},data:{acceptedJson:JSON.stringify(item.variants.map(v=>v.answer)),correctAnswer:(item.variants.find(v=>v.points===item.maximumPoints)??item.variants[0]).answer,maximumPoints:item.maximumPoints,explanation:item.explanation,active:item.active}});await tx.answerVariant.deleteMany({where:{exerciseItemId:item.id}});for(const variant of item.variants){await tx.answerVariant.create({data:{exerciseItemId:item.id,answer:variant.answer,normalized:normalizeAnswer(variant.answer),points:Math.min(variant.points,item.maximumPoints),source:'ADMIN'}})}}},{timeout:60000});return NextResponse.json({ok:true})}catch(e){return apiError(e)}}
