"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { Bell, Bookmark, BookmarkCheck, Check, ChevronLeft, ChevronRight, Menu, PencilLine, Send, Wifi } from "lucide-react";
import { countWords } from "@/lib/scoring/normalize";
import { inferWordLimit } from "@/lib/scoring/word-limit";
import { cn } from "@/lib/utils";

type Item={id:string;externalId:string;number:number;prompt:string;options:{key:string;label:string}[];keyword?:string|null;baseWord?:string|null;maximumPoints:number;displayOrder:number;answer:string};
type SetData={id:string;externalId:string;section:string;part:number;type:string;level:string;title:string;instructions:string;fullText:string;sourcePages:string;transcriptionStatus:string;notes:string;itemCount:number;testGroup:string;items:Item[]};
type AttemptData={attempt:{id:string;status:string;startedAt:string|Date;timeSpentSeconds:number;currentItemExternalId?:string|null};sets:SetData[]};

export function ExamRunner({data}:{data:AttemptData}){
 const router=useRouter(); const allItems=useMemo(()=>data.sets.flatMap(s=>s.items.map(i=>({...i,setId:s.externalId,part:s.part}))),[data.sets]);
 const initialIndex=Math.max(0,allItems.findIndex(i=>i.externalId===data.attempt.currentItemExternalId));
 const [index,setIndex]=useState(initialIndex); const [answers,setAnswers]=useState<Record<string,string>>(()=>Object.fromEntries(allItems.map(i=>[i.id,i.answer]))); const [marked,setMarked]=useState<Set<string>>(new Set()); const [saved,setSaved]=useState("Saved"); const [submitting,setSubmitting]=useState(false);
 const startedRef=useRef(Date.now()-data.attempt.timeSpentSeconds*1000); const [elapsed,setElapsed]=useState(data.attempt.timeSpentSeconds); const debounce=useRef<Record<string,ReturnType<typeof setTimeout>>>({});
 const current=allItems[index]; const set=data.sets.find(s=>s.externalId===current.setId)!;
 useEffect(()=>{const t=setInterval(()=>setElapsed(Math.floor((Date.now()-startedRef.current)/1000)),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{const warn=()=>{void save(current.id,answers[current.id]??"",current.externalId,true)};window.addEventListener('pagehide',warn);return()=>window.removeEventListener('pagehide',warn)});
 async function save(itemId:string,answer:string,currentExternalId:string,keepalive=false){setSaved('Saving…');try{const r=await fetch(`/api/attempts/${data.attempt.id}/answers`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({itemId,answer,elapsedSeconds:elapsed,currentItemExternalId:currentExternalId}),keepalive});setSaved(r.ok?'Saved':'Save failed')}catch{setSaved('Save failed')}}
 function update(item:Item,value:string,immediate=false){setAnswers(a=>({...a,[item.id]:value}));if(debounce.current[item.id])clearTimeout(debounce.current[item.id]);if(immediate)void save(item.id,value,item.externalId);else debounce.current[item.id]=setTimeout(()=>void save(item.id,value,item.externalId),550)}
 function go(next:number){if(next<0||next>=allItems.length)return;void save(current.id,answers[current.id]??"",allItems[next].externalId);setIndex(next);window.scrollTo({top:0,behavior:'smooth'})}
 async function submit(){const unanswered=allItems.filter(i=>!(answers[i.id]??'').trim()).length;if(!window.confirm(unanswered?`You still have ${unanswered} unanswered question${unanswered===1?'':'s'}. Submit anyway?`:'Submit this attempt? You will not be able to change your answers afterwards.'))return;setSubmitting(true);const r=await fetch(`/api/attempts/${data.attempt.id}/submit`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({elapsedSeconds:elapsed})});if(r.ok)router.replace(`/attempt/${data.attempt.id}/results`);else{setSubmitting(false);alert('The attempt could not be submitted. Please try again.')}}
 const answeredCount=allItems.filter(i=>(answers[i.id]??'').trim()).length;
 return <div className="flex min-h-screen flex-col bg-[#f4f7f8] text-[#11191d]">
  <ExamHeader elapsed={elapsed} saved={saved}/>
  <div className="border-b border-slate-300 bg-white px-4 py-3"><div className="mx-auto max-w-[1740px]"><b>Questions {set.items[0]?.number}–{set.items.at(-1)?.number}</b><p className="mt-1 text-sm">{instructionForPart(set.part)}</p></div></div>
  <main className="mx-auto flex w-full max-w-[1780px] flex-1 flex-col px-3 pb-28 pt-5 lg:px-4">
   <div className="mb-4 flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-[#007f86]">{set.section==='UOE'?'Use of English':'Reading'} · Part {set.part}</p><h1 className="mt-1 text-2xl font-bold">{set.title}</h1></div><button aria-pressed={marked.has(current.id)} onClick={()=>setMarked(m=>{const n=new Set(m);if(n.has(current.id)){n.delete(current.id)}else{n.add(current.id)}return n})} className="rounded-md p-2 hover:bg-slate-200" aria-label="Mark question">{marked.has(current.id)?<BookmarkCheck className="text-[#007f86]"/>:<Bookmark/>}</button></div>
   {[1,2,3].includes(set.part)?<InlineExercise set={set} answers={answers} update={update} currentId={current.id}/>:set.part===4?<KwtExercise item={current} instructions={set.instructions} answer={answers[current.id]??''} update={v=>update(current,v)}/>:<ReadingExercise set={set} item={current} answer={answers[current.id]??''} answers={answers} update={v=>update(current,v,true)}/>} 
  </main>
  <BottomNavigation sets={data.sets} allItems={allItems} index={index} answers={answers} marked={marked} answeredCount={answeredCount} onGo={go} onSubmit={submit} submitting={submitting}/>
 </div>
}
function ExamHeader({elapsed,saved}:{elapsed:number;saved:string}){const m=Math.floor(elapsed/60),s=elapsed%60;return <header className="border-b border-slate-300 bg-white"><div className="mx-auto flex h-[68px] max-w-[1780px] items-center px-4"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-sm bg-[#007f86] font-black text-white">C1</div><div><b className="block text-lg leading-5">C1 Practice Lab</b><span className="text-xs text-slate-500">Candidate practice mode</span></div></div><div className="ml-auto flex items-center gap-5"><span className="hidden items-center gap-1.5 text-xs text-slate-500 sm:flex"><Check size={15}/>{saved}</span><span className="rounded border border-slate-300 bg-slate-50 px-3 py-1.5 font-mono text-sm" aria-label="Elapsed time">{String(m).padStart(2,'0')}:{String(s).padStart(2,'0')}</span><Wifi size={22}/><Bell size={22}/><Menu size={24}/><PencilLine size={21}/></div></div></header>}
function instructionForPart(part:number){return ({1:'For each question, choose the correct answer for each gap.',2:'For each question, write the correct answer. Write one word for each gap.',3:'Use the word in CAPITALS to form a word that fits in the gap.',4:'Complete the second sentence using between three and six words, including the word given.',5:'Read the text and choose the correct answer for each question.',6:'Read the four texts and choose the reviewer that matches each statement.',7:'Choose the paragraph which fits each gap. There is one extra paragraph.',8:'Choose the section or consultant that matches each statement.'} as Record<number,string>)[part]}
function preparePassage(set:SetData){let text=set.fullText;const titleAt=text.indexOf(set.title);if(titleAt>=0)text=text.slice(titleAt+set.title.length).trim();if(set.part===1){const n=set.items[0]?.number;const idx=text.search(new RegExp(`\\n${n}\\s+A\\s+`));if(idx>0)text=text.slice(0,idx)}if(set.part===5){const n=set.items[0]?.number;const idx=text.search(new RegExp(`\\n${n}\\s+`));if(idx>0)text=text.slice(0,idx)}return text.replace(/\n{3,}/g,'\n\n').trim()}
function InlineExercise({set,answers,update,currentId}:{set:SetData;answers:Record<string,string>;update:(i:Item,v:string,immediate?:boolean)=>void;currentId:string}){const text=preparePassage(set);const map=new Map(set.items.map(i=>[i.number,i]));const chunks:React.ReactNode[]=[];let last=0;const re=/\((\d{1,3})\)\s*\.{2,}/g;let m:RegExpExecArray|null;while((m=re.exec(text))){chunks.push(text.slice(last,m.index));const n=Number(m[1]);const item=map.get(n);if(item)chunks.push(<InlineControl key={item.id} part={set.part} item={item} value={answers[item.id]??''} active={item.id===currentId} onChange={v=>update(item,v,set.part===1)}/>);else chunks.push(m[0]);last=re.lastIndex}chunks.push(text.slice(last));return <section className="relative rounded-md bg-white p-1 sm:p-3"><div className="max-w-[1600px] whitespace-pre-wrap text-[16px] leading-[3.05] sm:text-[17px]">{chunks}</div>{set.part===3&&<aside className="mt-6 rounded-md border border-slate-200 bg-slate-50 p-4"><b>Keyword list</b><div className="mt-2 grid gap-1 sm:grid-cols-2 lg:grid-cols-4">{set.items.map(i=><span key={i.id} className="text-sm"><b>{i.number}.</b> {i.baseWord??'—'}</span>)}</div></aside>}</section>}
function InlineControl({part,item,value,active,onChange}:{part:number;item:Item;value:string;active:boolean;onChange:(v:string)=>void}){if(part===1)return <span className="relative mx-1 inline-flex align-middle"><select aria-label={`Question ${item.number}`} value={value} onChange={e=>onChange(e.target.value)} className={cn('h-8 min-w-36 rounded border bg-white px-2 text-center font-semibold leading-normal',active?'border-[#007f86] ring-2 ring-teal-100':'border-slate-400')}><option value="">{item.number}</option>{item.options.map(o=><option key={o.key} value={o.key}>{o.key} · {o.label}</option>)}</select></span>;return <span className="mx-1 inline-flex align-middle"><input aria-label={`Question ${item.number}`} value={value} onChange={e=>onChange(e.target.value.toUpperCase())} placeholder={String(item.number)} className={cn('h-8 w-36 rounded border bg-white px-2 text-center font-semibold uppercase leading-normal',active?'border-[#007f86] ring-2 ring-teal-100':'border-slate-400')}/>{part===3&&<span className="ml-1 self-center text-xs font-bold text-slate-500">{item.baseWord}</span>}</span>}
function KwtExercise({item,instructions,answer,update}:{item:Item;instructions:string;answer:string;update:(v:string)=>void}){let prompt:{original?:string;second?:string}={};try{prompt=JSON.parse(item.prompt)}catch{prompt={original:item.prompt,second:''}}const wc=countWords(answer);const limit=inferWordLimit(instructions);const valid=wc===0||!limit||(wc>=limit.min&&wc<=limit.max);const keywordUsed=!answer||!item.keyword||answer.toUpperCase().split(/\s+/).includes(item.keyword.toUpperCase());return <section className="min-h-[530px] rounded-md bg-white p-6 lg:p-9"><p className="max-w-4xl text-lg leading-8">{prompt.original}</p><div className="my-7 text-lg font-black uppercase">{item.keyword}</div><div className="flex max-w-5xl flex-wrap items-center gap-3 text-lg leading-9"><span>{prompt.second?.split(/\.{3,}/)[0]}</span><input autoFocus value={answer} onChange={e=>update(e.target.value)} aria-label={`Answer for question ${item.number}`} className="min-w-64 flex-1 border-b-2 border-[#007f86] bg-teal-50/40 px-3 py-2 font-semibold uppercase"/><span>{prompt.second?.split(/\.{3,}/).slice(1).join(' ')}</span></div><div className="mt-5 flex flex-wrap gap-3 text-sm"><span className={cn('rounded-full px-3 py-1',valid?'bg-teal-50 text-teal-800':'bg-red-50 text-red-700')}>{wc} words{limit?` · required ${limit.min}–${limit.max}`:''}</span><span className={cn('rounded-full px-3 py-1',keywordUsed?'bg-teal-50 text-teal-800':'bg-red-50 text-red-700')}>{keywordUsed?'Keyword included':'Use the keyword unchanged'}</span></div></section>}
function parsePrompt(item:Item){const lines=item.prompt.split(/\r?\n/).map(l=>l.trim()).filter(Boolean);const question=lines[0]?.replace(/^\d+[.)]?\s*/,'')??`Question ${item.number}`;let options=item.options;if(!options.length){options=[];for(const line of lines.slice(1)){const m=line.match(/^([A-G])\s+(.+)$/);if(m)options.push({key:m[1],label:m[2]})}}return {question,options}}
function ReadingExercise({set,item,answer,answers,update}:{set:SetData;item:Item;answer:string;answers:Record<string,string>;update:(v:string)=>void}){const {question,options}=parsePrompt(item);const usedElsewhere=new Set(set.part===7?set.items.filter(candidate=>candidate.id!==item.id).map(candidate=>answers[candidate.id]).filter(Boolean):[]);return <section className="grid min-h-[590px] overflow-hidden rounded-md border border-slate-200 bg-white lg:grid-cols-[1.02fr_1fr]"><article className="exam-scroll max-h-[68vh] overflow-y-auto border-b border-slate-300 p-5 lg:border-b-0 lg:border-r"><h2 className="mb-4 text-2xl font-bold">{set.title}</h2><div className="whitespace-pre-wrap text-[15px] leading-6">{preparePassage(set)}</div></article><aside className="exam-scroll max-h-[68vh] overflow-y-auto p-5 lg:p-7"><h3 className="text-lg font-bold"><span className="mr-2 inline-grid h-7 min-w-7 place-items-center rounded border-2 border-[#008b95] px-1 text-sm">{item.number}</span>{question}</h3><fieldset className="mt-5 space-y-3"><legend className="sr-only">Select an answer</legend>{options.map(o=>{const unavailable=usedElsewhere.has(o.key);return <label key={o.key} className={cn('flex gap-3 rounded-md border p-4',unavailable?'cursor-not-allowed border-slate-200 bg-slate-100 text-slate-400':'cursor-pointer hover:bg-slate-50',answer===o.key&&'border-[#007f86] bg-teal-50 text-slate-900')}><input type="radio" name={item.id} value={o.key} checked={answer===o.key} disabled={unavailable} onChange={()=>update(o.key)} className="mt-1 h-4 w-4 accent-[#007f86]"/><span><b className="mr-2">{o.key}</b>{o.label===o.key?optionGeneric(set.part,o.key):o.label}{unavailable&&<small className="ml-2 font-semibold">Already used</small>}</span></label>})}</fieldset></aside></section>}
function optionGeneric(part:number,key:string){return part===6?`Reviewer ${key}`:part===8?`Section ${key}`:`Paragraph ${key}`}
function BottomNavigation({sets,allItems,index,answers,marked,answeredCount,onGo,onSubmit,submitting}:{sets:SetData[];allItems:Array<Item&{setId:string;part:number}>;index:number;answers:Record<string,string>;marked:Set<string>;answeredCount:number;onGo:(n:number)=>void;onSubmit:()=>void;submitting:boolean}){return <footer className="fixed inset-x-0 bottom-0 z-40 border-t border-slate-300 bg-white shadow-[0_-3px_12px_rgba(0,0,0,.08)]"><div className="mx-auto flex h-[76px] max-w-[1780px] items-stretch overflow-x-auto"><button onClick={()=>onGo(index-1)} disabled={index===0} className="grid min-w-16 place-items-center bg-slate-100 disabled:opacity-40" aria-label="Previous question"><ChevronLeft/></button><div className="flex min-w-max flex-1">{sets.map(s=>{const items=allItems.filter(i=>i.setId===s.externalId);const done=items.filter(i=>(answers[i.id]??'').trim()).length;return <div key={s.externalId} className={cn('flex items-center gap-1 border-l border-slate-200 px-3',items.some(i=>allItems[index]?.id===i.id)?'bg-white':'bg-[#f2f4f5]')}><span className="mr-2 whitespace-nowrap text-sm font-bold">Part {s.part}</span>{items.map(i=>{const idx=allItems.findIndex(x=>x.id===i.id);return <button key={i.id} onClick={()=>onGo(idx)} aria-label={`Question ${i.number}`} className={cn('relative grid h-8 min-w-7 place-items-center rounded px-1 text-sm',idx===index?'border-2 border-[#007f86] bg-white font-bold':answers[i.id]?.trim()?'bg-teal-100 text-teal-900':'hover:bg-slate-200')}>{i.number}{marked.has(i.id)&&<span className="absolute -right-0.5 -top-0.5 h-2 w-2 rounded-full bg-amber-500"/>}</button>})}<span className="ml-2 whitespace-nowrap text-xs text-slate-500">{done} of {items.length}</span></div>})}</div><button onClick={()=>onGo(index+1)} disabled={index===allItems.length-1} className="grid min-w-16 place-items-center bg-[#007f86] text-white disabled:bg-slate-300" aria-label="Next question"><ChevronRight/></button><button onClick={onSubmit} disabled={submitting} className="flex min-w-28 items-center justify-center gap-2 border-l bg-white px-4 font-bold text-[#006f76] hover:bg-teal-50"><Send size={18}/>{submitting?'Submitting':`Submit (${answeredCount}/${allItems.length})`}</button></div></footer>}
